# Generated by Django 3.2.3 on 2021-05-17 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 14, 4, 33, 798557), verbose_name='Дата публикации'),
        ),
    ]
