# Generated by Django 3.2.3 on 2021-05-17 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210517_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 21, 32, 34, 19735), verbose_name='Дата публикации'),
        ),
    ]
