# Generated by Django 3.2.3 on 2021-05-17 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 22, 7, 19, 724189), verbose_name='Дата публикации'),
        ),
    ]
